# For more information: https://laravel.com/docs/sail
version: '3'
services:
  laravel:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: lasail-8.0/app
    environment:
      WWWUSER: '${WWWUSER}'
    volumes:
      - '.:/var/www'
    networks:
      - sail
    depends_on:
      - mysql
      - redis
  nginx:
    image: nginx:alpine
    volumes:
      - '.:/var/www'
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - laravel
    networks:
      - sail
    ports:
      - '${APP_PORT:-80}:80'
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sailmysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sailredis:/data'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'sailmeilisearch:/data.ms'
    networks:
      - sail
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
        - sail
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      PMA_HOST: 'mysql'
      PMA_USER: 'root'
      PMA_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - /sessions
    ports:
      - '${PMA_PORT:-81}:80'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
  sailredis:
    driver: local
  sailmeilisearch:
    driver: local
