#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ ! -d /var/run/sail ]; then
    mkdir /var/run/sail
    chown sail:sail /var/run/sail
fi

if [ ! -f /var/log/php8.0-fpm.log ]; then
    touch /var/log/php8.0-fpm.log
    chown sail:sail /var/log/php8.0-fpm.log
fi

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
